config/routes.rb
Rails.application.routes.draw do

    root "events#index"

  devise_for :users
  resources :users
  resources :events

  resources :events do
    resources :attendances
    resources :pictures, only: [:create]

  end

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  after_create :new_attendance_email

  belongs_to :user
  belongs_to :event

  def new_attendance_email
    event = self.event
    event_admin = event.event_admin
    UserMailer.new_attendance_email(event_admin, event).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :event_admin, class_name: "User"

  validates :start_date, presence: true, inclusion: { in: (Date.today..Date.today+5.years) }
  validates :duration, presence: true, numericality: { greater_than_or_equal_to: 1 }, if: :multiple_of_five?
  validates :title, presence: true, length: { in: 5..40 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, :inclusion => 1..1000
  validates :location, presence: true

  has_one_attached :picture

  def multiple_of_five?
    errors.add(:duration, "La durée doit être un multiple de 5") unless duration % 5 == 0
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send


  has_many :attendances
  has_many :events, through: :attendances
  has_many :admin_events, foreign_key: "event_admin_id", class_name: "Event", dependent: :destroy

  has_one_attached :avatar

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :amounts



  def new
  end

  def index
    @attendances = Attendance.all
  end

  def create

    begin
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @stripe_amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
        })

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance_path
    end

    Attendance.create(user: current_user, event: @event, stripe_customer_id: customer.id)

  end

  def index
    @event = Event.find_by(id: params[:event_id])
    @attendances = @event.attendances

  end


  def is_admin?
      @event = Event.find_by(id: params[:event_id])
      redirect_to root_path unless @event.is_admin?(current_user)
  end


  private

  def amounts
    @event = Event.find(params[:event_id])
    @amount = @event.price
    @stripe_amount = @amount * 100
  end




end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  before_action :is_admin?, only: [:edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(post_params)
    @event.event_admin = current_user

    if @event.save
      redirect_to event_path(@event.id)
      flash[:success] = "Evénement créé avec succès !"
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])

  end

  def update
    @event = Event.find(params[:id])
    if @event.update(post_params)
      redirect_to event_path(@event.id)
      flash[:notice] = "Event édité !"
    else
      flash.now[:alert] = "Impossible d'éditer l'évènement' :"
      render :edit
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to root_path
  end



  private

    def authenticate_user
      unless current_user
        flash[:danger] = "Il faut s'enregistrer bb"
        redirect_to new_user_session_path
      end
    end

    def post_params
      post_params = params.require(:event).permit(:start_date, :title, :duration, :description, :price, :location, :picture)
    end

    def is_admin?
    @event = Event.find(params[:id])
      unless @event.event_admin == current_user
        redirect_to @event, danger: "Pas touche, c'est pas ton event !"
      end
    end

    def can_subscribe?
      @event = Event.find_by(id: params[:event_id])
      if @event.users.select{ |user| user == current_user }.count == 0
        return true
      else
        redirect_to event_path(@event), danger: "Tu es déjà inscrit !"
      end
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def create

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def check_user
     @user = User.find(params[:id])
     unless current_user.id == @user.id
        redirect_to root_path

     end
  end

  def show
    check_user
    @user = User.find(params[:id])
    @events = Event.where(event_admin: @user)
  end


  def edit
    @user = current_user

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Profil édité !"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "Impossible d'éditer le profil :"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end


end

app/helpers/attendances_helper.rb
module AttendancesHelper

end

app/helpers/avatars_helper.rb
module AvatarsHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<div class="container">
  <div class="text-center">
    <br>
    <h2 class="text-primary">Merci, tu as bien payé <strong><%=@amount%> euros</strong> !</h2>
    <%= link_to "Retourner sur la page de l'évènement", event_path(@event.id), class: "nav-link"  %>
  </div>
</div>

app/views/attendances/index.html.erb
<div class="container">
  <div class="text-center">
    <br>
    <h2> Mon espace admin <br> <i><%= @event.title %></i></h2>
      <br>
      <h3> Liste des participants</h3>

   <div class="row justify-content-center">

      <% @attendances.each do |attendance| %>
        <div class="card border-primary mx-auto" style="max-width: 20rem;">
          <div class="card-body">
            <h6 class="font-weight-light"><%= attendance.user.first_name + " " + attendance.user.last_name%> </h6>
              <blockquote class="blockquote text-center">
                <p class="mb-0 text-secondary"><%= attendance.user.description%></p>
                <footer class="blockquote-footer text-secondary"><%= attendance.user.email%></footer>
              </blockquote>
          </div>
        </div>
      <%end%>
    </div>
        <br><br>
        <%= link_to "Modifier l'évènement", edit_event_path(@event.id) , class: "btn btn-primary"%>
        <%= link_to "Supprimer l'événement", event_path(@event.id) , class: "btn btn-danger", :method => 'DELETE', :data => {:confirm => "Tu es sûr de vouloir supprimer l'événement?"} %>




  <div>
</div>

app/views/attendances/new.html.erb
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <%= form_tag event_attendances_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

  <div class="card border-info mx-auto" style="max-width: 20rem;">
   <div class="card-header"><span>Event : <%= @event.title %></span></div>
    <div class="card-body">
      <h4 class="card-title"><%= @amount %> euros</h4>
        <p class="card-text">Durée : <%= @event.duration %> minutes <br> Date : <%= @event.start_date %></p>
    </div>
  </div>
  <br>
    <p class="text-info">Alors ? C'est parti ?</p>
    </article>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Tu t'inscris à <%= @event.title %>?"
          data-amount=<%= @stripe_amount %>
          data-currency= 'eur'
          data-locale="fr"></script>
<% end %>

</div>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
    <%= form_with(model: @event, local: true) do |form| %>

      <div class="form-group">
        <%= form.label :On_commence_quand_? %>
        <%= form.datetime_field :start_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :on_y_reste_combien_de_temps_? %>
        <%= form.number_field :duration, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :comment_on_appelle_ton_event_? %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :tell_me_more %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :how_much_do_you_want_? %>
        <%= form.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :on_va_où_? %>
        <%= form.text_field :location, class: "form-control" %>
      </div>

        <div class="actions mt-5">
        <%= form.submit "Mettre à jour", class: "btn btn-lg btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">

  <%= render "shared/jumbotron" %>

  <div class="row">
      <% @events.each_with_index do |event, i| %>
        <div class="card border-primary mb-4 mx-auto" style="max-width: 20rem;">
          <div class="card-header"> Event <%= event.id %></div>
            <div class="card-body">
              <h4 class="card-title"><%= event.title %></h4>
                <p class="card-text"><%= event.description %></p>

              <%= link_to "Découvre l'évènement", event_path(event.id), class: "nav-link"  %>
            </div>
        </div>
      <% end %>
  </div>
</div>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger text-center" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
    <%= form_with(model: @event, local: true) do |form| %>

      <div class="form-group">
        <%= form.label :start_time ,"On commence quand ?" %>
        <%= form.datetime_field :start_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :duration, "On y reste combien de temps ?" %>
        <%= form.number_field :duration, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :title, "Comment on appelle ton event ?" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description, "Tell me more, tell me more..." %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :price, "Combien c'est ?" %>
        <%= form.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :location, "On va où ?" %>
        <%= form.text_field :location, class: "form-control" %>
      </div>

        <div class="form-group">
          <%= form.file_field :picture, direct_upload: true, class: "form-control" %>
        </div>


        <div class="actions mt-5">
        <%= form.submit "C'est parti pour le show", class: "btn btn-lg btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= render 'shared/banner'%>
<div class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <p class="lead">Event <%=params[:id]%> : <%= @event.title %></p>
    <h2><%= @event.attendances.count %> <%= (@event.attendances.count) == 1 ? 'Participant' : 'Participants'%></h2>

    <!-- Picture -->
    <%if @event.picture.attached?%>
      <%= image_tag @event.picture, alt: 'picture' %>
    <%else%>
      <img src="https://picsum.photos/200" class="rounded-circle">
    <%end%>

    <br><br><br>
    <!-- GOSSIP -->
    <h6 class="font-weight-bold">Date : <span class="text-muted"><%= @event.start_date %></span></h6>
    <h6 class="font-weight-bold">Durée : <span class="text-muted"><%= @event.duration %></span></h6>
    <h6 class="font-weight-bold">Prix : <span class="text-muted"><%= @event.price %></span></h6>
    <h6 class="font-weight-bold">Lieu : <span class="text-muted"><%= @event.location %></span></h6>
    <h6 class="font-weight-bold">Crée par : <span class="text-muted"><%= @event.event_admin.first_name %> <%= @event.event_admin.last_name %></span></h6>
    <br><br>
    <h6 class="font-weight-bold"><span class="text-secondary"><%= @event.description %></span></h6>


    <br>


    <% if @event.users.select{ |user| user == current_user }.count != 0 && current_user != @event.event_admin%>
      <p class="text-primary">Tu participes déjà à cet event ! </p>
    <% elsif current_user == @event.event_admin %> <p class="text-primary">Mazel Tov, tu es administrateur de cet event !</p>
      <%= link_to "Mon espace Admin", event_attendances_path(@event.id), :class => "btn btn-lg btn-primary" %>
    <% elsif current_user == nil %> <p class="text-danger">
      Tu dois être connecté.e pour t'inscrire à cet event !</p>
    <% else%>
      <%= link_to "Participer à cette dinguerie", new_event_attendance_path(@event.id), :class => "btn btn-lg btn-primary" %>

    <%end%>

  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
 <br><br><br>
  <footer class="pt-4 border-top">
    <div class="row">
      <div class="col-3 col-md">
      <center>
        <h5>Nous contacter</h5>
           <%= image_tag("fb.png", {:style => "width:50px;"}) %>
           <%= image_tag("insta.png", {:style => "width:50px;"}) %>
      </div>
      <div class="col-3 col-md">
        <h5>Mon compte</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Créer un event</a></li>
          <li><a class="text-muted" href="#">Modifier mes infos</a></li>
          <li><a class="text-muted" href="#">Voir les events</a></li>
        </ul>
      </div>

     <div class="col-3 col-md">
      <h5>Les baux légaux</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Conditions</a></li>
        <li><a class="text-muted" href="#">Confidentialité</a></li>
        <li><a class="text-muted" href="#">Cookies</a></li>
      </ul>
      </div>
      <div class="col-3 col-md">
        <center>
           <%= image_tag("moon.png", {:style => "width:50px;"}) %>

          <small class="text-muted">EventFlop &copy; 2020-2021</small></center>
      </div>
    </div>

  </footer>

app/views/layouts/_header.html.erb
 <!-- NAVBAR -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to "EventFlop", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Créer un événement", new_event_path, :class => "nav-item nav-link" %>
          </li>
        </ul>

        <div class="dropdown">
          <% if current_user == nil %>
            <button type="button" class="btn btn-light">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">S'inscrire / Se connecter</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" <%= link_to "Se connecter", new_user_session_path, :class => "nav-item nav-link" %></a>
                <a class="dropdown-item" <%= link_to "S'inscrire", new_user_registration_path, :class => "nav-item nav-link" %></a>
              </div>
            </button>
          <% else %>
            <form type="button" class="btn btn-light">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon profil</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" <%= link_to "Mon profil", user_path(current_user.id), :class => "nav-item nav-link" %></a>
                <a class="dropdown-item" <%= link_to "Se déconnecter", destroy_user_session_path, :class => "btn btn-outline-danger", :method => 'DELETE' %></a>
              </div>
            </form>
          <% end %>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <script src="https://kit.fontawesome.com/0fca16543f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/minty/bootstrap.min.css" integrity="sha384-H4X+4tKc7b8s4GoMrylmy2ssQYpDHoqzPa9aKXbDwPoPUA3Ra8PA5dGzijN+ePnH" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>EventFlop</title>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>

    <%= yield %>

     <%= render 'layouts/footer' %>


   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
      <div class="jumbotron jumbotron-fluid background-image" id="banner">
        <h1 style="color:white;">Des events hyper bof</h1>
        </div>
      </div>

app/views/shared/_jumbotron.html.erb
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3" style="color:white;" >EventFlop</h1>
          <h3 style="color:white;">Des events hyper bof</h3>
          <a href="" type="button" class="btn btn-light">CTA OKLM</a>
          <br/><br/>
        </div>
      </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for @user, html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifer mon profil</h1>
        <div class="form-group">
          <%= f.label :first_name, "Nom" %><br />
          <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, "Nom de famille" %><br />
          <%= f.text_field:last_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Mettre à jour", class: "btn btn-md btn-primary btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="text-center">
    <br>
    <h1> Profil </h1>
    <br>
    <!--image-->
      <div class="avatar mx-auto white">
        <h3>Votre photo actuelle</h3>
    <%if @user.avatar.attached? %>
      <%= image_tag @user.avatar, alt: 'avatar', class:"rounded-circle" %>
    <%else%>
      <img src="https://picsum.photos/200" class="rounded-circle">
    <%end%>
        </div>
    <br>

      <h3>Changer de photo ?</h3>
  <%= form_tag user_avatars_path(@user), multipart: true do %>
    <%= file_field_tag :avatar%>
    <%= submit_tag "mettre à jour" %>
  <% end %>

    <!--text-->


    <div class="card-body">
      <hr>

      <h6 class="font-weight-light">Prénom : <p class="text-secondary"><% if current_user.first_name != nil%> <%= @user.first_name%></p> <% end%>
      <h6 class="font-weight-light">Nom : <p class="text-secondary"><% if current_user.last_name != nil%> <%= @user.last_name%></p> <% end%>

      <br>



      <div class="card border-primary mx-auto" style="max-width: 20rem;">
        <div class="card-body">
          <h6 class="font-weight-light">Description : </h6>
            <blockquote class="blockquote text-center">
              <p class="mb-0 text-secondary"><% if current_user.description != nil%> <%= @user.description%></p> <% end%></p>
              <footer class="blockquote-footer text-secondary">Toi, <cite title="Source Title">Quand tu as écrit cette description</cite></footer>
            </blockquote>
        </div>
      </div>



      <br>
      <h6 class="font-weight-light">Email: <p class="text-secondary"><%= @user.email %></p>

      <%= link_to "Editer mes informations", edit_user_path(@user), :class => "btn btn-primary" %>
      <%= link_to "Editer mes identifiants", edit_user_registration_path(@user), :class => "btn btn-secondary" %>


    </div>
  </div>
</div>